version: '2'
services:
    client-net:
        build: web-client-core-asp.net
        ports:
        - "80:80"
        image: "jtony/web-client-core-asp:1.0"
    api-net:
        build: api-core.net
        ports:
        - "81:80"
        image: "jtony/api-core.net:1.0"
    api-node:
        build: api-node.js
        ports:
        - "82:80"
        image: "jtony/api-node.js:1.0"
    db-mongo:
        image: "mongo:3.0.3"
        ports:
        - "27017:27017"
    haproxy:
        image: "jtony/haproxy:1.0"
        links:
        - api-net
        - api-node
